# Generated by Django 5.0.4 on 2024-05-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(max_length=200),
        ),
    ]
